

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddTeacherForm.java
 *
 * Created on Jul 29, 2009, 11:37:24 AM
 */

/**
 *
 * @author Bryan
 */

import java.util.*;

public class AddTeacherForm extends javax.swing.JFrame {

    private DBHandler db;
    private Vector<String> teachers;
    private javax.swing.JComboBox teacherSelector;
    /** Creates new form AddTeacherForm */
    public AddTeacherForm(DBHandler db, Vector<String> teachers, javax.swing.JComboBox teacherSelector) {
        initComponents();
        this.db = db;
        this.teachers = teachers;
        this.teacherSelector = teacherSelector;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teacherAddName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnTeacherAdd = new javax.swing.JButton();

        teacherAddName.setColumns(255);

        jLabel1.setText("Teacher's Name");

        btnTeacherAdd.setText("Add Teacher");
        btnTeacherAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(teacherAddName, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnTeacherAdd)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teacherAddName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTeacherAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTeacherAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherAddActionPerformed

        //first check if they typed anything
        if(teacherAddName.getText().trim().equals(""))
        {
            javax.swing.JOptionPane.showMessageDialog(this, "You must enter a teacher name!");
            return;
        }

        Iterator itr = teachers.iterator();
        while(itr.hasNext())
        {
            String teach = (String)(itr.next());
            //make sure the teacher doesn't already exist
            if(teacherAddName.getText().trim().toLowerCase().equals(teach.trim().toLowerCase()))
            {
                javax.swing.JOptionPane.showMessageDialog(this, "The Teacher Name Already Exists!");
                return;
            }
        }

        if(teacherAddName.getText().length() < 256)
        {
            //they entered the correct number of characters
            //so add the teacher to the db
            db.addTeacher(teacherAddName.getText());
            //then add the teacher to our teacher list
            teachers.add(teacherAddName.getText());
            //and then add the teacher to the interface
            teacherSelector.addItem(teacherAddName.getText());
            this.setVisible(false);
        }
        else
        {
            //they entered too many characters
            javax.swing.JOptionPane.showMessageDialog(this, "The Name Was Too Long, it must be under 256 Characters.");
        }
    }//GEN-LAST:event_btnTeacherAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTeacherAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField teacherAddName;
    // End of variables declaration//GEN-END:variables

}
